export * from "./shared/service/topic.service"
export * from "./shared/interface/topic.interface"
export * from "./components/topic/topic.component"
export * from "./components/topic-form/topic-form.component"
export * from "./topic-management-routing.module"