export * from "./shared/service/qa.service"
export * from "./shared/interface/qa.interface"
export * from "./components/qa-dashboard/qa-dashboard.component"
export * from "./components/qa-form/qa-form.component"
export * from "./question-and-answer-routing.module"