export * from "./shared/service/course.service"
export * from "./shared/interface/course.interface"
export * from "./components/course-form/course-form.component"
export * from "./components/course-list/course-list.component"
export * from "./components/dashboard/dashboard.component"
export * from "./course-management-routing.module"